### ISSUE TITLE
sswe-u_tang.txt and reference_paper_we.txt, explanation???!!!

### ISSUE THREAD

**Issue by behnazeslami** [sgarda/nlp-adr#1]
@sgarda Hi,
Question???
In your github files, in this address **https://github.com/sgarda/nlp-adr/tree/master/data/we** there are two files : "**sswe-u_tang.txt**" and "**reference_paper_we.txt**"

Can you explain, how these files created? and what is the meaning of these files?

Thank you so much

**Comment by sgarda** [comment]
As in the read me file "sswe-u_tang.txt" contains word vectors computed with the algorithm presented in "D. Tang, F. Wei, N. Yang, M. Zhou, T. Liu, and B. Qin. Learning sentiment-specific word embedding for twitter sentiment classification". The word vectors are publicly available at  http://ir.hit.edu.cn/~dytang/. "reference_paper_we" are word vectors computed with word2vec on the corpus collected by "Sarker A, Gonzalez G; Portable Automatic Text Classification for Adverse Drug Reaction Detection via Multi-corpus Training, Journal of Biomedical Informatics, 2015 Feb;53:196-207. doi: 10.1016/j.jbi.2014.11.002. Epub 2014 Nov 8". Publicly available at http://diego.asu.edu/Publications/ADRMine.html
Both of them are used to initialize the embedding layer of the CNN architecture.
